---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 22577.
--- DateTime: 2023/11/29 17:09
---
if redis.call('sismember',KEYS[1],ARGV[1])==1 then
    redis.call('srem',KEYS[1],ARGV[1])
    local num = tonumber(redis.call('get', KEYS[2]))
    num=num-1
    redis.call('set',KEYS[2],num)
else
    redis.call('sadd',KEYS[1],ARGV[1])
    local num = tonumber(redis.call('get', KEYS[2]))
    num=num+1
    redis.call('set',KEYS[2],num)
end